
export const INJECTABLE = Symbol('INJECTABLE');
export const DEPENDENCIES = Symbol('DEPENDENCIES');
export const CONTROLLER_PREFIX = Symbol('CONTROLLER_PREFIX');
export const CONTROLLER_ROUTES = Symbol('CONTROLLER_ROUTES');
export const CONTROLLER_FILTERS = Symbol('CONTROLLER_FILTERS');
export const METHOD_PARAMS = Symbol('METHOD_PARAMS');
export const METHOD_GUARDS = Symbol('METHOD_GUARDS');
export const METHOD_INTERCEPTORS = Symbol('METHOD_INTERCEPTORS');
export const FILTER_ERROR_TYPES = Symbol('FILTER_ERROR_TYPES');
